name: example
description: Demo app for God of Flutter Printer package.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  god_of_flutter_printer:
    path: ../god_of_flutter_printer
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
